### PR TITLE
support laravel 8

### PR DESCRIPTION
**Pull request by faustbrian**

### CODE REVIEW

**Review by aradhell — APPROVED** [review]

**Comment by martinduefrandsen** [comment]
+1

**Comment by aat2703** [comment]
When will this PR be merged? 🥇

**Comment by aat2703** [comment]
@faustbrian 🧐

**Comment by aat2703** [comment]
@maguilar92 can you help 😍

**Comment by kohlerdominik** [comment]
@maguilar92 thanks for merging this
however, I think the release is currently missing, meaning the version contract `7.0` does not work?

**Comment by maguilar92** [comment]
@kohlerdominik It's merged at tag 8.0.0.

**Pull request merged**
