### PR TITLE
Laravel 5.8 support

### PR DESCRIPTION
**Pull request by squiaios**

### CODE REVIEW

**Comment by maguilar92** [comment]
@squiaios I will review and merge it today.

Thanks!

**Comment by squiaios** [comment]
@maguilar92 thanks, I did not change : 
- README file due to the Lifecycle information 
- Travis.yml because you have to create branch 5.8

**Comment by maguilar92** [comment]
@squiaios Now is published as 5.8.*

Thanks!

**Comment by drewkennelly** [comment]
Has this been published yet? When I try an install via composer, it says 5.8 is not available.

**Comment by maguilar92** [comment]
@drewkennelly I published the realease as you can see at: https://github.com/Askedio/laravel-soft-cascade/releases

But in packagist is not published: https://packagist.org/packages/askedio/laravel-soft-cascade

@gcphost Can you force in packagist to synchronize?

**Comment by maguilar92** [comment]
@gcphost There is a same issue in other package, this link can help you: https://github.com/squizlabs/PHP_CodeSniffer/issues/2168#issue-363545835

Seems that you must logout/login with GitHub to let upgrade the auto-update hooks and remove the deprecated GitHub service hooks

**Comment by drewkennelly** [comment]
Any update on this?

**Comment by maguilar92** [comment]
@drewkennelly I'm waiting @gcphost response for that. I can not do changes on Integration&Service and WebHooks to fix packagist integration.

**Comment by maguilar92** [comment]
@drewkennelly The only option I can offer to you is that you create a fork meanwhile.

**Comment by exodusanto** [comment]
@maguilar92 or use vcs on `composer.json`

```
...
    "require": {
        "askedio/laravel-soft-cascade": "^5.8",
...
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/Askedio/laravel-soft-cascade"
        }
    ],
...
```

**Comment by maguilar92** [comment]
@exodusanto That's true, I'm waiting for @gcphost to make the necessary changes. I will wait a while and if I see that it does not respond I will create a fork with the changes in packagist.

**Pull request merged**
