### PR TITLE
add belongs to relation to soft cascade

### PR DESCRIPTION
**Pull request by rybakk**
Fix belongsTo relations cascade soft delete

### CODE REVIEW

**Comment by maguilar92** [comment]
@rybakk Can you create an integration test?

**Comment by rybakk** [comment]
Yes, i'm gonna do this.

**Comment by maguilar92** [comment]
@rybakk Thank you!!!

**Comment by rybakk** [comment]
I failed to fix the error, I created the unit tests to trace the error.

**Comment by maguilar92** [comment]
@gcphost I need you to active 5.5 and 5.6 branches in travis-ci.org to check that all work before merge pull request.

Thanks.

**Comment by gcphost** [comment]
@maguilar92 it's locked in the config:
https://github.com/Askedio/laravel-soft-cascade/blob/master/.travis.yml#L18-L20

**Comment by gcphost** [comment]
Will code review shortly.

**Comment by maguilar92** [comment]
@rybakk I'm going to reverse the pull request.
BelongsTo relation is used for define the inverse of HasOne relationship. You must define the cascading in HasOne relationship.

**Pull request merged**
