### PR TITLE
Support Laravel 11

### PR DESCRIPTION
**Pull request by kohlerdominik**
Laravel 11 compatiblity should be no problem.

But as Laravel 11 RC is not out yet, this is just a draft.

### CODE REVIEW

**Comment by georgetassiano** [comment]
Laravel 11 has been released, can you update the compatibility?

**Comment by kohlerdominik** [comment]
@gcphost Can you rerun the Pipeline and merge, if successful?

**Comment by JustinElst** [comment]
I would love this too :)

**Comment by gcphost** [comment]
Done!

**Comment by kohlerdominik** [comment]
@gcphost Please also publish the release, if you're not already on it.

**Comment by gcphost** [comment]
Done!

**Pull request merged**
